# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7589142eac1f19328f48e4b03db74bdf8cdc7f67dce3968d8ff8b0e6c34c80195473079e689a023ce292c09e8a28a7a6ffa188037527647a11784291a87d2b

test:
  secret_key_base: 739a6c58a73c7e6c37a6971331ab5d5d72d8e3bfd8188e05cba0f994d13f592fb7469dcc9277660fd0726a430ab3200e09314efe2f72fc8702a013e9bf663641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
